---
kind: pipeline
name: Test
type: docker

steps:

  - name: lint
    image: node:buster
    volumes:
      - name: node_modules
        path: /usr/local/lib/node_modules
    commands:
      - npm install -g stylelint stylelint-config-standard jslint
      - npx stylelint "themes/crisp/css/*.css"
      - jslint "themes/crisp/js/!(*.min).js"

  - name: create_postgres_db
    image: postgres:9-alpine
    commands:
      - psql -h postgres -U postgres -c "CREATE DATABASE tosdr_dev;"

  - name: create_crisp_config
    image: alpine
    commands:
      - echo -e "MYSQL_HOSTNAME=postgres\n" > .env
      - echo -e "MYSQL_USERNAME=postgres\n" >> .env
      - echo -e "MYSQL_PASSWORD=postgres\n" >> .env
      - echo -e "MYSQL_DATABASE=tosdr_dev\n" >> .env
      - echo -e "REDIS_HOST=redis\n" >> .env
      - echo -e "REDIS_PORT=6379\n" >> .env


  - name: migrate_crisp_lint
    image: php:8.0-buster
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    commands:
      - mkdir /tmp/ci
      - cd /tmp/ci
      - apt-get update && apt-get install -y libpq-dev autoconf gcc libc6-dev make libicu-dev wget git-core zip zlib1g-dev libpng-dev
      - pecl install redis-5.3.2
      - docker-php-ext-install pgsql pdo_pgsql pdo_mysql intl gd gettext
      - docker-php-ext-enable pdo_pgsql pdo_mysql redis intl gd gettext
      - wget https://getcomposer.org/composer-stable.phar -O /tmp/ci/composer
      - cd /drone/src
      - php /tmp/ci/composer install
      - php bin/cli.php migrate
      - php bin/cli.php theme install crisp
      #  - vendor/bin/twig-linter lint themes/crisp/templates/
      #  - vendor/bin/phpunit tests --bootstrap tosdr/crisp.php
      - rm /tmp/ci/composer

  - name: Zip Production
    image: node:alpine
    commands:
      - apk --no-cache add zip bash
      - mkdir dist
      - zip -r dist/build.zip ./ -x '*.git*' -x 'tosdr/cache' -x '.env' -x 'static' -x '.vscode' -x 'dist' -x 'nbproject'
    when:
      branch:
        - master
      event:
        - push

  - name: Upload Build Artifacts
    image: plugins/s3
    settings:
      bucket: tosdr-artifacts
      source: ./dist/*
      strip_prefix: true
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      target: /CrispCMS/builds/${DRONE_BUILD_NUMBER}
      endpoint: https://s3.eu-west-2.jbcdn.net
    when:
      branch:
        - master
      event:
        - push

volumes:
  - name: bundle
    temp: {}
  - name: phoenix
    temp: {}
  - name: node_modules
    temp: {}

services:
  - name: redis
    image: redis
  - name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust

---
kind: pipeline
type: docker
name: Deploy
steps:

  - name: Deploy Production
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: SSH_HOST
      username:
        from_secret: SSH_USER
      key:
        from_secret: SSH_KEY
      port: 22
      script:
        - cd /usr/share/tosdr/web
        - /usr/bin/php bin/cli.php maintenance on
        - /usr/bin/git fetch origin master
        - /usr/bin/git reset --hard HEAD
        - /usr/bin/git merge ${DRONE_COMMIT_SHA}
        - /usr/local/bin/composer update
        - /usr/local/bin/composer install
        - /usr/bin/php bin/cli.php migrate
        - /usr/bin/php bin/cli.php theme storage refresh crisp
        - /usr/bin/php bin/cli.php theme translations refresh crisp
        - /usr/bin/php bin/cli.php plugin storage refresh management
        - /usr/bin/php bin/cli.php plugin translations refresh management
        - /usr/bin/php bin/cli.php cache clear
        - /usr/bin/php bin/cli.php maintenance off
    when:
      target:
        include:
          - staging
          - production

  - name: Deploy Staging
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: SSH_HOST
      username:
        from_secret: SSH_USER
      key:
        from_secret: SSH_KEY
      port: 22
      script:
        - cd /usr/share/tosdr/staging
        - /usr/bin/php bin/cli.php maintenance on
        - /usr/bin/git fetch origin master
        - /usr/bin/git reset --hard HEAD
        - /usr/bin/git merge ${DRONE_COMMIT_SHA}
        - /usr/local/bin/composer update
        - /usr/local/bin/composer install
        - /usr/bin/php bin/cli.php migrate
        - /usr/bin/php bin/cli.php theme storage refresh crisp
        - /usr/bin/php bin/cli.php theme translations refresh crisp
        - /usr/bin/php bin/cli.php plugin storage refresh management
        - /usr/bin/php bin/cli.php plugin translations refresh management
        - /usr/bin/php bin/cli.php cache clear
        - /usr/bin/php bin/cli.php maintenance off
    when:
      target:
        include:
          - staging

  - name: Jira Production
    image: plugins/jira
    settings:
      client_id:
        from_secret: jira_client_id
      client_secret:
        from_secret: jira_client_secret
      project: CRISP
      instance: tosdr
      environment: production
    when:
      target:
        include:
          - production
      
  - name: Jira Staging
    image: plugins/jira
    settings:
      client_id:
        from_secret: jira_client_id
      client_secret:
        from_secret: jira_client_secret
      project: CRISP
      instance: tosdr
      environment: staging
    when:
      target:
        include:
          - staging

trigger:
  branch:
    - master
  event:
    include:
      - promote
depends_on:
  - Test

---
kind: signature
hmac: 4f211cc052785f20d2beb2c5b77e9b8839b239cd84b91b016c2a9ca9997bfaad
...
