kind: pipeline
name: default

steps:
- name: Test Redis
  image: redis
  commands:
  - sleep 15
  - redis-cli -h redis ping

- name: Test MySQL
  image: mariadb
  commands:
  - sleep 15
  - mysql -u tosdr_dev -h mariadb -ptosdr_dev --execute="SELECT VERSION();"
  
- name: Create Config
  image: alpine
  commands:
  - echo -e "MYSQL_HOSTNAME=mariadb\n" >> .env
  - echo -e "MYSQL_USERNAME=tosdr_dev\n" >> .env
  - echo -e "MYSQL_PASSWORD=tosdr_dev\n" >> .env
  - echo -e "MYSQL_DATABASE=tosdr_dev\n" >> .env
  - echo -e "MYSQL_DATABASE=tosdr_dev\n" >> .env
  - echo -e "REDIS_HOST=redis\n" >> .env
  - echo -e "REDIS_PORT=6379\n" >> .env
    
- name: Install Dependencies
  image: composer
  commands:
  - composer install

- name: Migrate Database
  image: php:7.4
  commands:
  - php bin/cli.php migrate
  
- name: Run Tests
  image: php:7.4
  commands:
  - vendor/bin/phpunit tests --bootstrap pixelcatproductions\crisp.php

services:
- name: redis
  image: redis
- name: mariadb
  image: mariadb
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: tosdr_dev
    MYSQL_PASSWORD: tosdr_dev
    MYSQL_USER: tosdr_dev

node:
    os: linux