kind: pipeline
name: default

steps:
    
- name: Clone Phoenix
  image: alpine/git
  volumes:
  - name: phoenix
    path: /phoenix
  commands:
  - git clone https://github.com/tosdr/edit.tosdr.org /phoenix
    
- name: Install Bundles
  image: ruby:2.6.5
  volumes:
  - name: bundle
    path: /usr/local/bundle
  - name: phoenix
    path: /phoenix
  environment:
    DATABASE_HOST: postgres
    DATABASE_USER: postgres
  commands:
  - cd /phoenix
  - gem install bundler
  - gem install rails
  - bundle install
  - rails db:create db:migrate

- name: Install Dependencies
  image: composer
  commands:
  - composer install

- name: Test Redis
  image: redis
  commands:
  - sleep 5
  - redis-cli -h redis ping

- name: Test MySQL
  image: mariadb
  commands:
  - sleep 10
  - mysql -u tosdr_dev -h mariadb -ptosdr_dev --execute="SELECT VERSION();"
  
- name: Create Config
  image: alpine
  commands:
  - echo -e "MYSQL_HOSTNAME=mariadb\n" > .env
  - echo -e "MYSQL_USERNAME=tosdr_dev\n" >> .env
  - echo -e "MYSQL_PASSWORD=tosdr_dev\n" >> .env
  - echo -e "MYSQL_DATABASE=tosdr_dev\n" >> .env
  - echo -e "REDIS_HOST=redis\n" >> .env
  - echo -e "REDIS_PORT=6379\n" >> .env
    

- name: Migrate and Run Tests
  image: php:7.4-buster
  commands:
  - apt-get update && apt-get install -y libpq-dev autoconf gcc libc6-dev make
  - pecl install redis-5.3.2
  - docker-php-ext-install pgsql pdo_pgsql pdo_mysql
  - docker-php-ext-enable pdo_pgsql pdo_mysql redis
  - php bin/cli.php migrate
  - php ./vendor/bin/phpunit tests --bootstrap pixelcatproductions/crisp.php

volumes:
- name: bundle
  temp: {}
- name: phoenix
  temp: {}
  
services:
- name: redis
  image: redis
- name: mariadb
  image: mariadb
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: tosdr_dev
    MYSQL_PASSWORD: tosdr_dev
    MYSQL_USER: tosdr_dev
- name: postgres
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_DB: postgres
    POSTGRES_HOST_AUTH_METHOD: trust

node:
    os: linux
    